[auth]
enabled = true

[auth.external.facebook]
enabled = true
client_id = "887661387458086"
secret = "fb41bffa7b19b8763f3048750cfac3a6"
redirect_uri = "http://localhost:3000/api/auth/facebook/callback"

[auth.external.twitter]
enabled = true
client_id = "r7QyrfIB5gAXDUIYQSNBCk6wR"
secret = "5l4vbMhIPQ2AZXuLPjx7YodNQGE1A9dkC4jocrUh2uaBvz2mQu"
redirect_uri = "http://localhost:3000/api/auth/twitter/callback"

[auth.external.google]
enabled = true
client_id = "1022489787850-akl4qatk0mlmnb89rhcdoukla49g4t2u.apps.googleusercontent.com"
secret = "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"
redirect_uri = "http://localhost:3000/api/auth/youtube/callback"
